#theme: jekyll-theme-cayman

remote_theme: scotte/jekyll-clean
exclude:
  - readme.md
  - .github/

header_pages:
  - index.html

author: Ricardo Martins
twitter_username: ricmmartins
github_username:  ricmmartins

plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
